config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :venues
  resources :individuals
  resources :organizations
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/individual.rb
class Individual < ApplicationRecord
  validates :first_name, :last_name, presence: true
  has_and_belongs_to_many :organizations
  has_and_belongs_to_many :venues
end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  before_action :set_individual, only: [:show, :edit, :update, :destroy]

  # GET /individuals
  # GET /individuals.json
  def index
    @individuals = Individual.all
  end

  # GET /individuals/1
  # GET /individuals/1.json
  def show
  end

  # GET /individuals/new
  def new
    @individual = Individual.new
  end

  # GET /individuals/1/edit
  def edit
  end

  # POST /individuals
  # POST /individuals.json
  def create
    @individual = Individual.new(individual_params)

    respond_to do |format|
      if @individual.save
        format.html { redirect_to @individual, notice: 'Individual was successfully created.' }
        format.json { render :show, status: :created, location: @individual }
      else
        format.html { render :new }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /individuals/1
  # PATCH/PUT /individuals/1.json
  def update
    respond_to do |format|
      if @individual.update(individual_params)
        format.html { redirect_to @individual, notice: 'Individual was successfully updated.' }
        format.json { render :show, status: :ok, location: @individual }
      else
        format.html { render :edit }
        format.json { render json: @individual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individuals/1
  # DELETE /individuals/1.json
  def destroy
    @individual.destroy
    respond_to do |format|
      format.html { redirect_to individuals_url, notice: 'Individual was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_individual
      @individual = Individual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def individual_params
      params.require(:individual).permit(:first_name, :last_name, :job_title, :email, :phone, :comments)
    end
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/views/individuals/_form.html.erb
<%= form_with(model: individual, local: true) do |form| %>
  <% if individual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(individual.errors.count, "error") %> prohibited this individual from being saved:</h2>

      <ul>
      <% individual.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :job_title %>
    <%= form.text_field :job_title %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/individuals/edit.html.erb
<h1>Editing Individual</h1>

<%= render 'form', individual: @individual %>

<%= link_to 'Show', @individual %> |
<%= link_to 'Back', individuals_path %>

app/views/individuals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Individuals</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Job title</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @individuals.each do |individual| %>
      <tr>
        <td><%= individual.first_name %></td>
        <td><%= individual.last_name %></td>
        <td><%= individual.job_title %></td>
        <td><%= individual.email %></td>
        <td><%= individual.phone %></td>
        <td><%= individual.comments %></td>
        <td><%= link_to 'Show', individual %></td>
        <td><%= link_to 'Edit', edit_individual_path(individual) %></td>
        <td><%= link_to 'Destroy', individual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Individual', new_individual_path %>

app/views/individuals/new.html.erb
<h1>New Individual</h1>

<%= render 'form', individual: @individual %>

<%= link_to 'Back', individuals_path %>

app/views/individuals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @individual.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @individual.last_name %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @individual.job_title %>
</p>

<p>
  <strong>Email:</strong>
  <%= @individual.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @individual.phone %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @individual.comments %>
</p>

<%= link_to 'Edit', edit_individual_path(@individual) %> |
<%= link_to 'Back', individuals_path %>